services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    volumes:
      # Enlazamos tu carpeta data local con la carpeta data del contenedor
      - ./data:/app/data
    restart: always

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000/api/v1/metrics/macro
    depends_on:
      - api
    restart: always