services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./api:/app/api
    restart: always

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000/api/v1/metrics/macro
    volumes:
      - ./dashboards:/app/dashboards
    depends_on:
      - api
    restart: always