FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copiar la carpeta del dashboard interactivo
COPY dashboards/ ./dashboards/

# Exponer el puerto nativo de Streamlit
EXPOSE 8501

# Comando para arrancar Streamlit configurando el puerto y la interfaz correcta
CMD ["streamlit", "run", "dashboards/main.py", "--server.port", "8501", "--server.address", "0.0.0.0"]